import type { Metadata } from "next";
import "./globals.css";
import { CursorProvider } from "./context/cursorCtx";
import ClientCursor from "./components/clientCursor";
import { IBM_Plex_Mono } from "next/font/google";
import ParticleBackground from "./components/backGround";
import { Toaster } from "sonner";

const IBM_Font = IBM_Plex_Mono({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IBM_Font.className} antialiased bg-gray-900`}
      >
        <CursorProvider>
          <ParticleBackground/>
          <ClientCursor />
         
          {children}
          <Toaster richColors position="top-right" />
        </CursorProvider>
      </body>
    </html>
  );
}
